# Generated by Django 4.0.4 on 2022-05-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fechaDeNacimiento', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaDeSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mismaSangre', models.CharField(max_length=20)),
                ('relacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Yo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miNombre', models.CharField(max_length=20)),
                ('miApellidos', models.CharField(max_length=20)),
                ('mifechaDeNacimiento', models.DateField(blank=True)),
            ],
        ),
    ]
