# Generated by Django 4.0.4 on 2022-05-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisFamiliares', '0002_alter_familiar_fechadenacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fechaDeNacimiento',
        ),
        migrations.RemoveField(
            model_name='yo',
            name='mifechaDeNacimiento',
        ),
    ]
