# Generated by Django 4.0.4 on 2022-05-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisFamiliares', '0003_remove_familiar_fechadenacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='yo',
            name='miApellidos',
        ),
        migrations.RemoveField(
            model_name='yo',
            name='miNombre',
        ),
        migrations.AddField(
            model_name='familiar',
            name='NombreCompleto',
            field=models.CharField(default='z', max_length=30),
        ),
        migrations.AddField(
            model_name='yo',
            name='miNombreCompleto',
            field=models.CharField(default='x', max_length=30),
        ),
    ]
